- hosts: localhost
  gather_facts: no
  vars_files:
    # - "vars/credentials.yaml"
    - "vars/setup.yaml"
    #- "vars/gslbState.desired.yaml"
  pre_tasks:
   
    - name: Create AWS credentials
      ansible.builtin.shell: "aws configure set aws_access_key_id {{AWS_ACCESS_KEY_ID}} --profile test"
    
    - name: Create AWS credentials
      ansible.builtin.shell: "aws configure set aws_secret_access_key {{AWS_SECRET_ACCESS_KEY}} --profile test"

    - name: Test AWS Credentials
      ansible.builtin.shell: "aws ec2 describe-regions --profile test"

    - name: Create Kubeconfig
      ansible.builtin.shell: "aws eks --region us-east-1 update-kubeconfig --name {{item}}"
      loop: "{{target_clusters}}"